server.port: 8091
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true